// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_gold_level = "CgkI97LjhN0SEAIQDQ"; // <GPGSID>
        public const string achievement_release_the_beast_i = "CgkI97LjhN0SEAIQFw"; // <GPGSID>
        public const string achievement_gold_miner_ii = "CgkI97LjhN0SEAIQFQ"; // <GPGSID>
        public const string achievement_release_the_beast_ii = "CgkI97LjhN0SEAIQGA"; // <GPGSID>
        public const string achievement_crystals_farmer_iii = "CgkI97LjhN0SEAIQEw"; // <GPGSID>
        public const string leaderboard_highscore = "CgkI97LjhN0SEAIQAQ"; // <GPGSID>
        public const string achievement_quest_hunter_iii = "CgkI97LjhN0SEAIQHA"; // <GPGSID>
        public const string achievement_crystals_farmer_i = "CgkI97LjhN0SEAIQEQ"; // <GPGSID>
        public const string event_score = "CgkI97LjhN0SEAIQBQ"; // <GPGSID>
        public const string achievement_quest_hunter_i = "CgkI97LjhN0SEAIQGg"; // <GPGSID>
        public const string achievement_silver_level = "CgkI97LjhN0SEAIQDA"; // <GPGSID>
        public const string achievement_crystals_farmer_ii = "CgkI97LjhN0SEAIQEg"; // <GPGSID>
        public const string achievement_quest_hunter_ii = "CgkI97LjhN0SEAIQGw"; // <GPGSID>
        public const string achievement_gold_miner_i = "CgkI97LjhN0SEAIQFA"; // <GPGSID>
        public const string event_crystals_bonus_score = "CgkI97LjhN0SEAIQAg"; // <GPGSID>
        public const string achievement_gold_miner_iii = "CgkI97LjhN0SEAIQFg"; // <GPGSID>
        public const string achievement_platinum_level = "CgkI97LjhN0SEAIQDg"; // <GPGSID>
        public const string achievement_bronze_level = "CgkI97LjhN0SEAIQCw"; // <GPGSID>
        public const string achievement_lets_roll = "CgkI97LjhN0SEAIQAw"; // <GPGSID>
        public const string achievement_release_the_beast_iii = "CgkI97LjhN0SEAIQHQ"; // <GPGSID>
        public const string achievement_master_level = "CgkI97LjhN0SEAIQEA"; // <GPGSID>
        public const string event_player_level = "CgkI97LjhN0SEAIQBA"; // <GPGSID>
        public const string achievement_diamond_level = "CgkI97LjhN0SEAIQDw"; // <GPGSID>
        public const string achievement_reset = "CgkI97LjhN0SEAIQGQ"; // <GPGSID>

}

